#define ID_PROJECT_LOAD					1500
#define ID_PROJECT_NEW					1501
#define ID_PROJECT_SAVE					1502
#define ID_PROJECT_SAVEAS				1503
#define ID_PROJECT_CLOSE				1504

#define ID_LOADED_FILE					1700
#define ID_NUM_COLOURS					1701
#define ID_NUM_SPRITES					1702
#define ID_VIEWPAL						1703

#define ID_SPRITELOAD					1800
#define ID_SPRITESAVE					1801
#define ID_SPRITENUM					1802
#define ID_SPRITESIZE					1803
#define ID_SPRITEFIRST					1804
#define ID_SPRITEBACK					1805
#define ID_SPRITEFORWARD				1806
#define ID_SPRITELAST					1807
#define ID_SPRITEINSERT					1808
#define ID_SPRITEDELETE					1809
#define ID_SPRITECENTRE					1810
#define ID_MOVEHOTSPOT					1811
#define ID_SPRITETRIM					1812
#define ID_FIXAXIS						1813
#define ID_FONTIFY						1814
#define ID_SPRITEINSERTEMPTY			1815
#define ID_BANKTRIM						1816

// Extra stuff for palette dialog
#define ID_COLOUR_OFFSET				2000
#define ID_REMOVEUNUSED					2001
#define ID_SORTBRIGHT					2002
#define ID_ADDCOLOURS					2003

// Extra stuff for hotspot dialog
#define ID_X							2000
#define ID_Y							2001
#define ID_HOT_CENTRE					2002
#define	ID_HOT_BASE						2003

// Extra stuff for hotspot dialog
#define ID_FON_ADDSPACE					2000
#define ID_FON_SPACEWIDTH				2001
#define ID_FON_COLOURS					2002

