#define DIALOG_1			1
#define WARNINGDIALOG		2

#define IDI_ICON1			105
#define IDI_ICON2			106
#define ID_WARNINGLIST		3000

#define COM_CANCEL_BUTTON	2000
#define COM_PROJTEXT		2001
#define COM_PROGTEXT		2002
#define COM_FILENAME		2003
#define COM_ITEMTEXT		2004
#define COM_PERC1			2005
#define COM_PERC2			2006
#define COM_NUM_FUNC		2007
#define COM_NUM_OBJ			2008
#define COM_NUM_RES			2009
#define COM_NUM_GLOB		2010
#define COM_NUM_STRINGS		2011



#define DLG_MAIN						500
#define DLG_COMPILE                     501
#define DLG_FILE_LOCATIONS				600
#define DLG_WINDOW_SIZES				626
#define DLG_PROJECT_PROPERTIES			650
#define DLG_PROJECT_ADVANCED			651
#define DLG_PROJECT_RENDERING			652
#define DLG_SEARCH_RESULTS				999

#define ID_FILELIST						1000
#define ID_CONTENTS_ADD_FILE			1001
#define ID_CONTENTS_RESOURCES			1002
#define ID_CONTENTS_EDIT_FILE			1003
#define ID_CONTENTS_DELETE_FILE			1004
#define ID_CONTENTS_FIND_IN_FILE		1005

#define ID_PROJECT_LOAD					1500
#define ID_PROJECT_NEW					1501
#define ID_PROJECT_SAVE					1502
#define ID_PROJECT_SAVEAS				1503
#define ID_PROJECT_COMPILE				1504
#define ID_PROJECT_CLOSE				1506
#define ID_PROJECT_REVERT				1507

#define ID_LAUNCH_SPRITE				1551
#define ID_LAUNCH_Z						1552
#define ID_LAUNCH_TRANS					1553
#define ID_LAUNCH_FLOOR					1554
#define ID_LAUNCH_ENGINE				1555

#define ID_RENDERING_AA_DEF_ENABLED		1600
#define ID_RENDERING_AA_DEF_SOFT_X		1601
#define ID_RENDERING_AA_DEF_SOFT_Y		1602
#define ID_RENDERING_AA_MAX_ENABLED		1603
#define ID_RENDERING_AA_MAX_READINI		1604
#define ID_RENDERING_AA_MAX_SOFT_X		1605
#define ID_RENDERING_AA_MAX_SOFT_Y		1606

#define ID_UPGRADES						1590

#define ID_EXIT							1700
#define ID_ABOUT						1701
#define ID_SLUDGE_HELP					1702

#define ID_KEEP_IMAGES					1800
#define ID_KEEP_STRINGS					1801
#define ID_VERBOSE						1802

// These menu options open other dialog boxes...
#define ID_SETTINGSBOX					1850
#define ID_DISPLAY						1852
#define ID_SIZEBOX						1853

#define ID_LOADED_FILE					2000

// For the file locations dialog box...
#define ID_TEXT_EDITOR					2500
#define ID_TEXT_BROWSE					2501

// For the window size dialog box...
#define ID_USE_PROJECT_SIZE				2502

// For the display dialog box...
#define ID_EDIT_NAME					2001
#define ID_EDIT_OUTPUTFILE				2002
#define ID_EDIT_QUITMESSAGE				2003
#define ID_EDIT_WINWIDTH				2004
#define ID_EDIT_WINHEIGHT				2005
#define ID_EDIT_LANGUAGE				2500
#define ID_FULLSCREEN					2501
#define ID_EDIT_SPEED					2502
#define ID_EDIT_CUSTOMICON				2503
#define ID_MAKESILENT					2504
#define ID_EDIT_SPEED2					2200
#define ID_EDIT_DATAFOLDER				2201
#define ID_MOREOPTIONS					2202
#define ID_EDIT_CUSTOMLOGO				2199

#define ID_STARTUP_DISPLAY_SLUDGE		2203
#define ID_STARTUP_DISPLAY_LOADING		2204
#define ID_STARTUP_INVISIBLE			2205

#define ID_DITHERIMAGES					2206

#define ID_CASESENSITIVE				2600


#define ID_NUM_COLOURS					1701
#define ID_NUM_SPRITES					1702
#define ID_VIEWPAL						1703

#define ID_SPRITELOAD					1800
#define ID_SPRITESAVE					1801
#define ID_SPRITENUM					1802
#define ID_SPRITESIZE					1803
#define ID_SPRITEFIRST					1804
#define ID_SPRITEBACK					1805
#define ID_SPRITEFORWARD				1806
#define ID_SPRITELAST					1807
#define ID_SPRITEINSERT					1808
#define ID_SPRITEDELETE					1809
#define ID_SPRITECENTRE					1810
#define ID_MOVEHOTSPOT					1811
#define ID_SPRITETRIM					1812
#define ID_FIXAXIS						1813
#define ID_FONTIFY						1814
#define ID_SPRITEINSERTEMPTY			1815
#define ID_BANKTRIM						1816

// Extra stuff for palette dialog
#define ID_COLOUR_OFFSET				2000
#define ID_REMOVEUNUSED					2001
#define ID_SORTBRIGHT					2002
#define ID_ADDCOLOURS					2003

// Extra stuff for hotspot dialog
#define ID_X							2000
#define ID_Y							2001
#define ID_HOT_CENTRE					2002
#define	ID_HOT_BASE						2003

// Extra stuff for hotspot dialog
#define ID_FON_ADDSPACE					2000
#define ID_FON_SPACEWIDTH				2001
#define ID_FON_COLOURS					2002


#define ID_PROJECT_LOAD					1500
#define ID_PROJECT_UPDATE				1504

#define ID_HELP							1530
#define ID_SEARCH						1531

#define ID_CATEGORY						1550
#define ID_STRINGS						1551
#define ID_ENTER_TRANSLATION			1552
#define ID_GOT_TRANSLATION				1553
#define ID_UNDO							1554
#define ID_ORIGINAL_TEXT				1555
#define ID_FILENAME						1556
#define ID_ID							1557



