#ifndef CSLUDGE_H
#define CSLUDGE_H

enum sludgeCommand {SLU_UNKNOWN,
					SLU_RETURN, SLU_BRANCH, SLU_BR_ZERO, SLU_SET_GLOBAL,
					SLU_SET_LOCAL, SLU_LOAD_GLOBAL, SLU_LOAD_LOCAL,
					SLU_PLUS, SLU_MINUS, SLU_MULT, SLU_DIVIDE,
					SLU_AND, SLU_OR, SLU_EQUALS, SLU_NOT_EQ, SLU_MODULUS,
					SLU_LOAD_VALUE, SLU_LOAD_BUILT, SLU_LOAD_FUNC, SLU_CALLIT,
					SLU_LOAD_STRING, SLU_LOAD_FILE, /*SLU_LOAD_SCENE,*/ SLU_LOAD_OBJTYPE,
					SLU_NOT, SLU_LOAD_NULL, SLU_STACK_PUSH, SLU_LESSTHAN, SLU_MORETHAN, SLU_NEGATIVE,
					SLU_UNREG, SLU_LESS_EQUAL, SLU_MORE_EQUAL,
					SLU_INCREMENT_LOCAL,
					SLU_DECREMENT_LOCAL,
					SLU_INCREMENT_GLOBAL,
					SLU_DECREMENT_GLOBAL, SLU_INDEXSET, SLU_INDEXGET,
					SLU_INCREMENT_INDEX, SLU_DECREMENT_INDEX, SLU_QUICK_PUSH,
					numSludgeCommands};

#endif
