#define DIALOG_1			1
#define WARNINGDIALOG		2

#define IDI_ICON1			105
#define IDI_ICON2			106
#define ID_WARNINGLIST		3000

#define COM_CANCEL_BUTTON	2000
#define COM_PROJTEXT		2001
#define COM_PROGTEXT		2002
#define COM_FILENAME		2003
#define COM_ITEMTEXT		2004
#define COM_PERC1			2005
#define COM_PERC2			2006
#define COM_NUM_FUNC		2007
#define COM_NUM_OBJ			2008
#define COM_NUM_RES			2009
#define COM_NUM_GLOB		2010
#define COM_NUM_STRINGS		2011





