
#define ID_PROJECT_LOAD					1500
#define ID_PROJECT_SAVE					1501
#define ID_PROJECT_SAVEAS				1502
#define ID_PROJECT_NEW					1503
#define ID_PROJECT_UPDATE				1504
#define ID_PROJECT_REVERT				1505

#define ID_HELP							1530
#define ID_SEARCH						1531
#define ID_CASESENSITIVE				1532

#define ID_CATEGORY						1550
#define ID_STRINGS						1551
#define ID_ENTER_TRANSLATION			1552
#define ID_GOT_TRANSLATION				1553
#define ID_UNDO							1554
#define ID_ORIGINAL_TEXT				1555
#define ID_FILENAME						1556
#define ID_ID							1557



